### ISSUE TITLE
Is Python 3.6 supported?

### ISSUE THREAD

**Issue by cclauss** [pythad/selenium_extensions#3]
https://github.com/pythad/selenium_extensions/blob/master/setup.py#L42

Python 3.3 goes [EOL](https://docs.python.org/devguide/index.html#branchstatus) later this month.

**Comment by pythad** [comment]
`selenium_extensions` mainly depends on `selenium` and `pyvirtualdisplay` for Firefox headless mode support. In the docs I found that Selenium supports Python3.3+ an PyVirtualDisplay supports Python up to 3.5. But actually, there are no problems running PyVirtualDisplay using Python3.6. I think the reason for this is that Python3.5 is still the default Python on most distributions and `pyvirtualdisplay` doesn't get updated that much.

But the answer to your question is yes - Python3.6 is supported and you shouldn't face any problems.

**Comment by cclauss** [comment]
Great explanation.  Thanks.

**Comment by cclauss** [comment]
@pythad  Christmas comes early...  https://github.com/ponty/PyVirtualDisplay now supports Python 3.6

**Comment by pythad** [comment]
@cclauss That's great! I will add Python3.6 badge to supported versions.

Just checked the commit 'Added Python3.6 support' for `pyvirtualdisplay`. As I said, it just wasn't updated for some time, but there were nothing incompatible: https://github.com/ponty/PyVirtualDisplay/commit/dff144f26670dc193fbb95a26961372d5b6c765b
